name: Build
on:
  push:
    branches:
      - master
  pull_request: {}
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --check-files --frozen-lockfile
      - name: Test
        run: yarn test
      - name: Synthesize project files
        run: npx cdk synth
